name: 'ski_comparator'
version: '1.0.0'
config-version: 2

profile: 'ski_comparator'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ski_comparator:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
