version: 2

models:
  - name: dim_stations
    description: "Dimension station de ski"
    columns:
      - name: station_id
        tests:
          - not_null
          - unique

  - name: fct_enneigement_quotidien
    description: "Faits enneigement/météo quotidiens par station"

  - name: mart_score_qualite_neige
    description: "Score de qualité neige par station"
    columns:
      - name: station_id
        tests:
          - not_null
          - unique
      - name: score_qualite_neige
        tests:
          - not_null
